version: "3.8"

services:
  labrad:
    build:
      context: .
    volumes:
      - ./.labrad:/root/.labrad
      - ./lib:/root/lib
      - ../qubesrv:/root/lib/qubesrv
      - ./config:/root/config
      - ./script:/root/script
      - ./log:/root/log
      - ./work:/root/work
      - /data1/labrad-data:/root/labrad-data
      - ../../registry.sqlite:/root/config/registry.sqlite
    network_mode: "host"
    environment:
      - LABRADPORT=7682
